title: Wahaab Siddique
baseURL: /
params:

  [params.homepage_meta_tags]
    meta_description = "Welcome to the official website of Wahaab Siddique."
    meta_og_title = "Wahaab Siddique"
    meta_og_type = "website"
    meta_og_url = "https://wahaabsiddique.com"
    meta_og_description = "Welcome to the official website of Wahaab Siddique."
    meta_twitter_card = "summary"
    meta_twitter_site = "@wahaabsiddique"
    meta_twitter_creator = "@wahaabsidique"


<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-77218107-6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-77218107-6');
</script>


google_analytics_id = "UA-77218107-6"
  description: Wahaab Siddique's official website.
  palette: red
  favicon:
  title: Wahaab Siddique
  icon_path: /images/favicon.ico
  
  header:
 
    social_links:
      - type: action
        label: Twitter
        url: https://twitter.com/wahaabsiddique
        style: icon
        icon_class: fa-twitter
        new_window: true
      - type: action
        label: Instagram
        url: https://www.instagram.com/wahaabsiddique
        style: icon
        icon_class: fa-instagram
        new_window: true
      - type: action
        label: GitHub
        url: https://github.com/wahaab11
        style: icon
        icon_class: fa-github
        new_window: true
      - type: action
        label: LinkedIn
        url: https://www.linkedin.com/
        style: icon
        icon_class: fa-linkedin
        new_window: true
      - type: action
        label: DEV
        url: https://dev.to/wahaabsiddique
        style: icon
        icon_class: fa-dev
        new_window: true
    tagline: Welcome to the official website of Wahaab Siddique.
    logo_img: ""
    has_social: true
    background_img: /images/img_no_style_20200112_130447_processed.jpg
    title: Wahaab Siddique
    type: header
    nav_links:
      - type: action
        label: Home
        url: /
        style: link
      - type: action
        label: About
        url: /about/
        style: link
      - type: action
        label: Style Guide
        url: /style-guide/
        style: link
      - type: action
        label: Contact
        url: /contact/
        style: link
    has_nav: true
  footer:
    type: footer
    content: "&copy; All rights reserved. Email: contact@wahaabsiddique.com"
    links:
      - style: link
        new_window: false
        type: action
        url: https://wahaabsiddique.com
        label: Wahaab Siddique
        icon_class: ""
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
