title: Wahaab Siddique
baseURL: /
params:
  description: Wahaab Siddique's official website.
  palette: red
  header:
    social_links:
      - type: action
        label: Twitter
        url: https://twitter.com/wahaabsiddique
        style: icon
        icon_class: fa-twitter
        new_window: true
      - type: action
        label: Instagram
        url: https://www.instagram.com/wahaabsiddique
        style: icon
        icon_class: fa-instagram
        new_window: true
      - type: action
        label: GitHub
        url: https://github.com/wahaab11
        style: icon
        icon_class: fa-github
        new_window: true
      - type: action
        label: LinkedIn
        url: https://www.linkedin.com/
        style: icon
        icon_class: fa-linkedin
        new_window: true
      - type: action
        label: DEV
        url: https://dev.to/wahaabsiddique
        style: icon
        icon_class: fa-dev
        new_window: true
    tagline: ""
    logo_img: ""
    has_social: true
    background_img: /images/img_no_style_20200112_130447_processed.jpg
    title: ""
    type: header
    nav_links:
      - type: action
        label: Home
        url: /
        style: link
      - type: action
        label: About
        url: /about/
        style: link
      - type: action
        label: Style Guide
        url: /style-guide/
        style: link
      - type: action
        label: Contact
        url: /contact/
        style: link
    has_nav: true
  footer:
    type: footer
    content: "&copy; All rights reserved. Wahaab Siddique."
    links:
      - style: icon
        new_window: false
        type: action
        url: https://wahaabsiddique.com
        label: website
        icon_class: 4.jpg
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
